/*
 * AboutDialog.java
 *
 * Created on March 12, 1999, 1:59 PM
 *
 * Modification Log:
 *
 * 1.00  12th Mar 1999   Tanmay   Original version
 * 1.01  12th Jun 1999   Tanmay   Changed layout. Added icon.
 * 2.00  22nd Sep 2001   Tanmay   Moved over to Java Swing.
 *-----------------------------------------------------------------------------------------
 *       10th Sep 2003   Tanmay   Moved to SourceForge (http://classeditor.sourceforge.net)
 *-----------------------------------------------------------------------------------------
 *
 */

package gui;

/**
 * The About dialog. Dialog to show information about this utility.
 * <br>
 *
 * @author 	Tanmay K. Mohapatra
 * @version     2.00, 22nd September, 2001
 */

class AboutDialog extends java.awt.Dialog {
    
    /** Creates new form AboutDialog */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.GridBagLayout());

        setBackground(java.awt.Color.white);
        setResizable(false);
        setTitle("About ClassEditor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/large/classeditor.gif")));
        jLabel1.setText("ClassEditor Version 2.23");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        add(jLabel1, gridBagConstraints);

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setText("WebSite: http://classeditor.sourceforge.net/");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 45, 0, 10);
        add(jLabel2, gridBagConstraints);

        jTextArea1.setEditable(false);
        jTextArea1.setText("Current Version: 21st March, 2004\nOriginal Version: 12th March, 1999\n\nContributors:\nTanmay K. M.");
        jTextArea1.setBorder(null);
        jTextArea1.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 45, 10, 10);
        add(jTextArea1, gridBagConstraints);

        setBounds(50, 100, 340, 250);
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
