/*
 * ExceptionsAttribPanel.java
 *
 * Created on January 27, 2002, 4:15 PM
 *
 * Modification Log:
 * 1.00   27th Jan 2002   Tanmay   Original version.
 * 1.01   11th May 2002   Tanmay   Made the table single selection model
 *-----------------------------------------------------------------------------------------
 *       10th Sep 2003   Tanmay   Moved to SourceForge (http://classeditor.sourceforge.net)
 *-----------------------------------------------------------------------------------------
 */

package gui.attributes;

import classfile.*;
import classfile.attributes.Attribute;
import classfile.attributes.ExceptionsAttribute;
import guihelper.attributes.ExceptionsListTableModel;

import javax.swing.table.TableColumn;
import javax.swing.ListSelectionModel;

/**
 * Copyright (C) 2002-2003  Tanmay K. Mohapatra
 * <br>
 * @author 	Tanmay K. Mohapatra
 * @version     1.01, 11th May, 2002
 */
public class ExceptionsAttribPane extends javax.swing.JPanel implements AttribDisplay {

    private ExceptionsAttribute attribute;
    private ConstantPool constPool;
    private boolean bModifyMode;
    
    /** Creates new form ExceptionsAttribPanel */
    public ExceptionsAttribPane(boolean bModifyMode) {
        this.bModifyMode = bModifyMode;
        
        initComponents();
        btnAdd.setEnabled(bModifyMode);
        btnRemove.setEnabled(bModifyMode);
    }

    private void populateExceptions() {
        ExceptionsListTableModel thisModel = new ExceptionsListTableModel(constPool, attribute);
        tblExceptions.setModel(thisModel);
        thisModel.setEditable(bModifyMode);
        thisModel.setCellEditors(tblExceptions);
        
        TableColumn thisCol;
        
        thisCol = tblExceptions.getColumnModel().getColumn(0);
        thisCol.setPreferredWidth(30);
        thisCol.setMaxWidth(80);
        
        thisCol = tblExceptions.getColumnModel().getColumn(1);
        thisCol.setPreferredWidth(500);
        thisCol.setMaxWidth(800);        
    }

    public void setInput(Attribute attribute, ConstantPool constPool) {
        this.attribute = (ExceptionsAttribute)attribute;
        this.constPool = constPool;
        populateExceptions();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane2 = new javax.swing.JScrollPane();
        tblExceptions = new javax.swing.JTable();
        tblExceptions.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        tblExceptions.setModel(new guihelper.attributes.ExceptionsListTableModel(null, null));
        jScrollPane2.setViewportView(tblExceptions);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 1.0;
        add(jScrollPane2, gridBagConstraints1);
        
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        
        jPanel1.add(btnAdd);
        
        btnRemove.setText("Delete");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        
        jPanel1.add(btnRemove);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 1.0;
        add(jPanel1, gridBagConstraints1);
        
    }//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int iIndex = tblExceptions.getSelectedRow();
        if(iIndex < 0) return;
        
        attribute.deleteExceptionAt(iIndex);
        populateExceptions();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        ExceptionsListTableModel thisModel = (ExceptionsListTableModel)tblExceptions.getModel();
        thisModel.addNewExceptionEntry();
        populateExceptions();
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblExceptions;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    // End of variables declaration//GEN-END:variables

}
