/*
 * LocalVariableAttribPane.java
 *
 * Created on January 27, 2002, 4:55 PM
 *
 * Modification Log:
 * 1.00   27th Jan 2002   Tanmay   Original version.
 * 1.10   16th Mar 2002   Tanmay   Added edit facility.
 * 1.20   19th May 2002   Tanmay   Added a check for handling obfuscated classes
 *-----------------------------------------------------------------------------------------
 *       10th Sep 2003   Tanmay   Moved to SourceForge (http://classeditor.sourceforge.net)
 *-----------------------------------------------------------------------------------------
 */

package gui.attributes;

import classfile.*;
import classfile.attributes.LocalVariableTableAttribute;
import classfile.attributes.LocalVariableTableEntry;
import classfile.attributes.Attribute;
import guihelper.attributes.LocalVariableTableAttribTableModel;

import javax.swing.*;
import javax.swing.table.TableColumn;
import javax.swing.DefaultListModel;

/**
 * Copyright (C) 2002-2003  Tanmay K. Mohapatra
 * <br>
 *
 * @author 	Tanmay K. Mohapatra
 * @version     1.20, 19th May, 2002
 */
public class LocalVariableAttribPane extends javax.swing.JPanel implements AttribDisplay {
    
    private LocalVariableTableAttribute attribute;
    private ConstantPool constPool;
    private boolean bModifyMode;
    
    /** Creates new form LocalVariableAttribPane */
    public LocalVariableAttribPane(boolean bModifyMode) {
        this.bModifyMode = bModifyMode;
        
        initComponents();
        btnAdd.setEnabled(bModifyMode);
        btnDelete.setEnabled(bModifyMode);
    }
    
    public void setInput(Attribute attribute, ConstantPool constPool) {
        this.attribute = (LocalVariableTableAttribute)attribute;
        this.constPool = constPool;
        setTableModel();
    }
    
    private void checkForObfuscation() {
        if(bModifyMode) {
            int iMaxCount = attribute.vectLocalVariableTable.size();
            for (int iIndex=0; iIndex < iMaxCount; iIndex++) {
                LocalVariableTableEntry lvEntry = (LocalVariableTableEntry)attribute.vectLocalVariableTable.elementAt(iIndex);
                if((null == lvEntry.cpDescriptor) || (null == lvEntry.cpName)) {
                    bModifyMode = false;
                    JOptionPane.showMessageDialog(this, "Local variable table is invalid (probably obfuscated).\nHence it can not be edited.", "Class format invalid", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
            }
        }
    }
    
    private void setTableModel() {
        TableColumn thisCol;
        LocalVariableTableAttribTableModel thisModel = new LocalVariableTableAttribTableModel(attribute, constPool);
        
        checkForObfuscation();
        
        thisModel.setEditable(bModifyMode);
        tblLocalVariables.setModel(thisModel);
        thisModel.setCellEditors(tblLocalVariables);
        
        thisCol = tblLocalVariables.getColumnModel().getColumn(0);
        thisCol.setPreferredWidth(30);
        thisCol.setMaxWidth(80);
        
        thisCol = tblLocalVariables.getColumnModel().getColumn(1);
        thisCol.setPreferredWidth(200);
        thisCol.setMaxWidth(400);
        
        thisCol = tblLocalVariables.getColumnModel().getColumn(2);
        thisCol.setPreferredWidth(200);
        thisCol.setMaxWidth(400);
        
        thisCol = tblLocalVariables.getColumnModel().getColumn(3);
        thisCol.setPreferredWidth(50);
        thisCol.setMaxWidth(200);
        
        thisCol = tblLocalVariables.getColumnModel().getColumn(4);
        thisCol.setPreferredWidth(50);
        thisCol.setMaxWidth(200);
        
        tblLocalVariables.changeSelection(0, 1, false, false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLocalVariables = new javax.swing.JTable();
        tblLocalVariables.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        tblLocalVariables.setModel(new LocalVariableTableAttribTableModel(null, null));
        jScrollPane2.setViewportView(tblLocalVariables);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(10, 10, 10, 10);
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 1.0;
        add(jScrollPane2, gridBagConstraints1);
        
        jPanel1.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints2;
        
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(btnAdd, gridBagConstraints2);
        
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(btnDelete, gridBagConstraints2);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanel1, gridBagConstraints1);
        
    }//GEN-END:initComponents
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int iRow = this.tblLocalVariables.getSelectedRow();
        if(0 > iRow) return;
        
        attribute.deleteEntryAt(iRow);
        setTableModel();
    }//GEN-LAST:event_btnDeleteActionPerformed
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        ((LocalVariableTableAttribTableModel)tblLocalVariables.getModel()).addNewEntry();
        setTableModel();
    }//GEN-LAST:event_btnAddActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblLocalVariables;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    // End of variables declaration//GEN-END:variables
    
}
